@startuml

!include ../style.default.plantuml
!include actstyle.plantuml

|#FEFEFE|adm| Membro di amministrazione (admin, supervisor)
|#EDDDDD|fe| Front-end
|#FEFEFE|be| API Back-end

|fe|
partition #LightPink/White Messaggio di **errore** {
	#Pink:(E)
	:Visualizza un messaggio di errore inerente\nalla problematica che vi si è presentata;
	stop
}

|adm|
start
Note left
	Il membro dell'amministrazione
	(admin, supervisor) è autenticato 
end Note

:Si collega al pannello di amministrazione\nquindi richiede la pagina di rimozione\npietanze dal sistema;

|fe|
:Restituisce il pannello di amministrazione\nper la rimozione di pietanze dal sistema;

|adm|
repeat
	:Seleziona quale alimento rimuovere dal sistema;

	|fe|
	:Richiede conferma al membro di amministrazione tramite messaggio;

	|adm|
	if (Il membro di amministrazione conferma la cancellazione?) then (No)
		stop
	endif

	|be|
	:Validazione sulla pietanza selezionata;

	if (La pietanza indicata è valida?) then (No)
		#Pink:(E)
	endif

repeat while (La validazione ha riportato esito positivo?) is (No) Not (Si)

|be|
:La pietanza è rimossa dal sistema;

|fe|
:Segnala l'avvenuta cancellazione con successo;

stop
@enduml
