
@startuml
!include ../style.default.plantuml
!include actstyle.plantuml

|#FEFEFE|sv| Addetto alla cucina
|#EDDDDD|fe| Front-end
|#FEFEFE|be| API Back-end

|sv|
start
Note left
	L'addetto alla cucina è **autenticato**
	e vi è almeno un ordine nello stato __wait__
	assegnatogli
end Note

:Si collega al pannello di gestione della cucina;

|fe|
:Restituisce il pannello di gestione della cucina\nche indica lo stato degli ordini;

|sv|
repeat
:Seleziona uno tra gli ordini nello stato __wait__ disponibili e ne\nconferma l'effettuata preparazione delle pietanze al sistema;

	|fe|
	:Richiede conferma all'addetto di cucina;

	|sv|
repeat while (L'addetto alla cucina conferma il completamento?) is (No) Not (Si)

|be|
:L'ordine (e tutte le sue pietanze) assumono lo stato di __ready__;

|fe|
:Informa, con un messaggio, che l'ordine è completo\nquindi aggiorna l'interfaccia;

stop

@enduml
