@startuml

!include ../style.default.plantuml
!include statestyle.plantuml

state form as "Form Inserimento\nPietanza" #Gold
form: entry/VisualizzaFormInserimentoPietanza

state val as "Validazione" #LightGreen

state failhnd as "Error Handling" #LightPink 

[*]		-[hidden]d-> failmsg
[*]							-d-> form
form						-d-> val: CliccaPulsanteInserisci()
val							-d-> [*]: [OK] / RegistraNuovaPietanza()
val							-l-> failhnd: [Error]
failhnd					-u-> form

@enduml
