/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ratatouille23;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;

@SpringBootApplication
@EntityScan("database")
public class App {
    public static String getGreeting() {
        return "Rest API for RatatoApp is now starting...";
    }

    public static void main(String[] args) {
        System.out.println(App.getGreeting());
        SpringApplication.run(App.class, args);
    }

}
