@startuml

!include ../style.default.plantuml
!include seqstyle.plantuml

' Entities
actor "AdministrationMember:Employee" as adm #orange
control Frontend as fe
box "Backend Layer" #Lightgreen
	entity Backend as be
	database Database as db
end box

== Indirizzamento dinamico ==

adm -> fe ++: Richiedi controllo per inserimento dipendente
fe --> adm --: Restituisce un form di inserimento dipendente

== Compilazione del form ==

group#Gold #LightYellow Inserimento dati
	adm -> fe ++: Inserisce nome utente
	fe --> adm: Validazione preliminare campo nome
	note right 
		La validazione è un rapido controllo
		front-end che verifica la correttezza
		dei campi seguendo le guidelines
		descritte precedentemente
	end note

	adm -> fe: Richiede i ruoli dipendenti disponibili
	fe -> be ++: Ottieni i ruoli utenti disponibili
	be -> db ++: Effettua query per ottenerne i ruoli dipendenti disponibili
	db --> be --: Ritonra l'elenco delle categorie disponibili
	be --> fe --: Ritorna i ruoli dipendenti disponibili all'inserimento
	fe -> fe: Popola lista di ruoli dipendenti 

	adm -> fe: Seleziona ruolo dipendente dalla lista
	fe --> adm: Validazione preliminare ruolo dipendente
end

== Richiesta e finalizzazione dell'inserimento ==

adm -> fe: Pressione del pulsante di conferma di creazione
fe -> be ++: Ne richiede l'inserimento
be -> be: Generazione di una password (token) casuale
be -> be: Validazione della richiesta 
be -> db ++: Inserimento nuova pietanza

alt#Gold #Lightblue Inserimento avvenuto con successo
	db --> be --: Inserimento avvenuto correttamente
	be --> fe --: Riporta esito positivo nell'inserimento\nquindi ritorna la password generata
	fe --> fe: Visualizza la password appena generata
	fe --> adm --: Segnala l'avvenuto inserimento
	fe-[hidden]->fe
else #Pink Errore generico nell'inserimento
	activate db
	activate be
	activate fe

	db --> be --: Non è stato possibile completare l'operazione
	be -> fe --: Riporta esito negativo nell'inserimento
	fe --> adm --: Segnala il mancato inserimento
end

@enduml
